apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-ref-aws
  annotations:
    company: Upbound
    maintainer: Jared Watts <jared@upbound.io>
    keywords: aws, cloud-native, kubernetes, example, platform, reference
    source: github.com/upbound/platform-ref-aws
    license: Apache-2.0
    descriptionShort: |
      The AWS reference platform for Kubernetes and Data Services.

    description: |
      This reference platform `Configuration` for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.

    readme: |
      This reference platform `Configuration` for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.
      It provides platform APIs to provision fully configured EKS clusters,
      with secure networking, and stateful cloud services (RDS) designed to
      securely connect to the nodes in each EKS cluster -- all composed using
      cloud service primitives from the [Crossplane AWS
      Provider](https://doc.crds.dev/github.com/crossplane/provider-aws). App
      deployments can securely connect to the infrastructure they need using
      secrets distributed directly to the app namespace.

      [Quickstart
      Guide](https://github.com/upbound/platform-ref-aws/#quick-start)

      [APIs in this
      Configuration](https://github.com/upbound/platform-ref-aws/#apis-in-this-configuration)

      To learn more checkout the [GitHub
      repo](https://github.com/upbound/platform-ref-aws/) that you can copy and
      customize to meet the exact needs of your organization!

spec:
  crossplane:
    version: ">=v0.14.0-0"
  dependsOn:
    - provider: crossplane/provider-aws
      version: ">=v0.14.0-0"
