apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-ref-aws
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/platform-ref-aws
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This reference platform Configuration for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.

    meta.crossplane.io/readme: |
      This reference platform `Configuration` for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.
      It provides platform APIs to provision fully configured EKS clusters,
      with secure networking, and stateful cloud services (RDS) designed to
      securely connect to the nodes in each EKS cluster -- all composed using
      cloud service primitives from the [Upbound Official AWS
      Provider](https://marketplace.upbound.io/providers/upbound/provider-aws). App
      deployments can securely connect to the infrastructure they need using
      secrets distributed directly to the app namespace.

      To learn more checkout the [GitHub
      repo](https://github.com/upbound/platform-ref-aws/) that you can copy and
      customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-lb-controller
      # renovate: datasource=github-releases depName=upbound/configuration-aws-lb-controller
      version: "v0.1.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-network
      # renovate: datasource=github-releases depName=upbound/configuration-aws-network
      version: "v0.18.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-database
      # renovate: datasource=github-releases depName=upbound/configuration-aws-database
      version: "v0.11.1"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks
      # renovate: datasource=github-releases depName=upbound/configuration-aws-eks
      version: "v0.13.1"
    - configuration: xpkg.upbound.io/upbound/configuration-app
      # renovate: datasource=github-releases depName=upbound/configuration-app
      version: "v0.9.0"
    - configuration: xpkg.upbound.io/upbound/configuration-observability-oss
      # renovate: datasource=github-releases depName=upbound/configuration-observability-oss
      version: "v0.7.1"
    - configuration: xpkg.upbound.io/upbound/configuration-gitops-flux
      # renovate: datasource=github-releases depName=upbound/configuration-gitops-flux
      version: "v0.8.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.7.0"
