apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-aws-ghost
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  compositeDeletePolicy: Foreground
  parameters:
    helm:
      values:
        ingress:
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
          enabled: true
          ingressClassName: alb
        service:
          type: ClusterIP
      wait: true
    providerConfigName: platform-ref-aws
    passwordSecretRef:
      namespace: default
      name: platform-ref-aws-db-conn-mariadb
  writeConnectionSecretToRef:
    name: platform-ref-aws-ghost-conn
