apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: clusters.aws.platformref.upbound.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: aws.platformref.upbound.io/v1alpha1
    kind: Cluster
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-platform-ref-awscluster
    step: cluster
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
