apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.aws.platformref.upbound.io
spec:
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  group: aws.platformref.upbound.io
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                  passwordSecretRef:
                    type: object
                    description: "A reference to the Secret object containing database password"
                    properties:
                      namespace:
                        type: string
                      name:
                        type: string
                      key:
                        type: string
                    required:
                    - namespace
                    - name
                    - key
                  clusterRef:
                    type: object
                    description: "A reference to the Network object that this postgres should be
                    connected to."
                    properties:
                      id:
                        type: string
                        description: ID of the Network object this ref points to.
                    required:
                    - id
                required:
                  - storageGB
                  - clusterRef
                  - passwordSecretRef
            required:
              - parameters
