apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.aws.platformref.crossplane.io
  annotations:
    upbound.io/ui-schema: |-
      ---
      configSections:
      - title: Database Size
        description: Enter information to size your database
        items:
        - name: storageGB
          controlType: singleInput
          type: integer
          path: ".spec.parameters.storageGB"
          title: Storage (GB)
          description: The size in GB for database storage
          default: 5
          validation:
          - minimum: 1
          - maximum: 500
          - required: true
        - name: networkRef
          controlType: singleInput
          type: string
          path: ".spec.parameters.networkRef.id"
          title: Network Ref
          description: Network fabric to connect the database to
          default: platform-ref-aws-network
          validation:
          - required: true
            customError: Network ref is required and should match the network ref of the app cluster.
        - name: writeSecretRef
          controlType: singleInput
          type: string
          path: ".spec.writeConnectionSecretToRef.name"
          title: Connection Secret Ref
          description: name of the secret to write to this namespace
          default: db-conn
          validation:
          - required: true
spec:
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  group: aws.platformref.crossplane.io
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                  #networkRef:
                  #  type: object
                  #  description: "A reference to the Network object that this postgres should be
                  #  connected to."
                  #  properties:
                  #    id:
                  #      type: string
                  #      description: ID of the Network object this ref points to.
                  #  required:
                  #  - id
                required:
                  - storageGB
                  #- networkRef
            required:
              - parameters
