kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: upbound-system
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""