apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-aws-ghost
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  parameters:
    helm:
      chart:
        name: ghost
        repo: "https://charts.bitnami.com/bitnami"
        version: 23.0.25
      values:
        ingress:
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
          enabled: true
          ingressClassName: alb
        service:
          type: ClusterIP
      wait: true
    providerConfigName: platform-ref-aws
    passwordSecretRef:
      namespace: default
      name: platform-ref-aws-db-mariadb-sql
