apiVersion: aws.platformref.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-aws-ghost
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    providerConfigName: platform-ref-aws
    passwordSecretRef:
      namespace: default
      name: platform-ref-aws-db-conn-mariadb
  writeConnectionSecretToRef:
    name: platform-ref-aws-ghost-conn
