apiVersion: aws.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws
spec:
  id: platform-ref-aws
  parameters:
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "15.0.1"
  writeConnectionSecretToRef:
    name: platform-ref-aws-kubeconfig
