apiVersion: aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-release.sh
spec:
  id: platform-ref-aws
  parameters:
    region: us-east-1
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
    # deletionPolicy: Delete
  writeConnectionSecretToRef:
    name: platform-ref-aws-kubeconfig
