apiVersion: aws.platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: platform-ref-aws-db-mariadb
  namespace: default
spec:
  parameters:
    region: us-west-2
    engine: mariadb
    engineVersion: "10.11.14"
    storageGB: 5
    autoGeneratePassword: true
    passwordSecretRef:
      namespace: default
      name: mariadbsecret
      key: password
    networkRef:
      id: platform-ref-aws
  writeConnectionSecretToRef:
    name: platform-ref-aws-db-conn-mariadb
