apiVersion: aws.platformref.upbound.io/v1alpha1
kind: XCluster
metadata:
  name: platform-ref-aws
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  compositeDeletePolicy: Foreground
  writeConnectionSecretToRef:
    name: platform-ref-aws-kubeconfig
    namespace: default
  parameters:
    id: platform-ref-aws
    region: us-west-2
    version: "1.32"
    networkSelector: basic
    deletionPolicy: Delete
    providerConfigName: default
    nodes:
      count: 3
      instanceType: t3.small
    operators:
      flux:
        version: "2.10.6"
      fluxSync:
        version: "1.7.2"
      prometheus:
        version: "52.1.0"
    gitops:
      git:
        interval: "5m0s"
        timeout: "60s"
        url: https://github.com/upbound/platform-ref-aws/
        path: "/"
        ref:
          name: refs/heads/main
