apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.aws.platformref.upbound.io
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.platformref.upbound.io/v1alpha1
    kind: XNetwork
  patchSets:
  - name: network-id
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.id
      toFieldPath: metadata.labels[networks.aws.platformref.upbound.io/network-id]
  resources:
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            region: us-west-2
            cidrBlock: 192.168.0.0/16
            enableDnsSupport: true
            enableDnsHostnames: true
            tags:
              Owner: Platform Team
              Name: platformref-vpc
      name: platformref-vcp
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: InternetGateway
        spec:
          forProvider:
            region: us-west-2
            vpcIdSelector:
              matchControllerRef: true
      name: gateway
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: us-west-2a
            access: public
        spec:
          forProvider:
            region: us-west-2
            mapPublicIpOnLaunch: true
            cidrBlock: 192.168.0.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: us-west-2a
            tags:
              kubernetes.io/role/elb: "1"
      name: subnet-public-west-2a
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: us-west-2b
            access: public
        spec:
          forProvider:
            region: us-west-2
            mapPublicIpOnLaunch: true
            cidrBlock: 192.168.64.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: us-west-2b
            tags:
              kubernetes.io/role/elb: "1"
      name: subnet-public-west-2b
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: us-west-2a
            access: private
        spec:
          forProvider:
            region: us-west-2
            cidrBlock: 192.168.128.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: us-west-2a
            tags:
              kubernetes.io/role/internal-elb: "1"
      name: subnet-private-west-2a
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: us-west-2b
            access: private
        spec:
          forProvider:
            region: us-west-2
            cidrBlock: 192.168.192.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: us-west-2b
            tags:
              kubernetes.io/role/internal-elb: "1"
      name: subnet-private-west-2b
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: us-west-2
            vpcIdSelector:
              matchControllerRef: true
      name: routeTable
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Route
        spec:
          forProvider:
            region: us-west-2
            destinationCidrBlock: 0.0.0.0/0
            gatewayIdSelector:
              matchControllerRef: true
            routeTableIdSelector:
              matchControllerRef: true
      name: route
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: MainRouteTableAssociation
        spec:
          forProvider:
            region: us-west-2
            routeTableIdSelector:
              matchControllerRef: true
            vpcIdSelector:
              matchControllerRef: true
      name: mainRouteTableAssociation
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            region: us-west-2
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2a
                access: public
      name: RouteTableAssociation-public-a
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            region: us-west-2
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2b
                access: public
      name: RouteTableAssociation-public-b
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            region: us-west-2
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2a
                access: private
      name: RouteTableAssociation-private-a
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        spec:
          forProvider:
            region: us-west-2
            routeTableIdSelector:
              matchControllerRef: true
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2b
                access: private
      name: RouteTableAssociation-private-b
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            region: us-west-2
            vpcIdSelector:
              matchControllerRef: true
            name: platform-ref-aws-cluster
            description: Allow access to PostgreSQL
      name: securityGroup
      patches:
        - type: PatchSet
          patchSetName: network-id
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            region: us-west-2
            type: ingress
            fromPort: 5432
            toPort: 5432
            protocol: tcp
            cidrBlocks:
              - 0.0.0.0/0
            securityGroupIdSelector:
              matchControllerRef: true
            description: Everywhere
      name: securityGroupRule
      patches:
        - type: PatchSet
          patchSetName: network-id
